# Generated by Django 5.1.4 on 2024-12-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members_id', models.IntegerField()),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('phone_num', models.IntegerField()),
                ('email', models.TextField()),
            ],
        ),
    ]
