# Generated by Django 5.1.4 on 2024-12-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trainers_id', models.IntegerField()),
                ('Name', models.TextField()),
                ('Address', models.TextField()),
                ('Expertise', models.TextField()),
                ('Phone_number', models.IntegerField()),
                ('Email', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='members',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='members_id',
            new_name='Members_id',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='phone_num',
            new_name='Phone_number',
        ),
    ]
