# Generated by Django 5.1.4 on 2024-12-24 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_trainers_rename_address_members_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
        migrations.RenameModel(
            old_name='Trainers',
            new_name='Trainer',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Members_id',
            new_name='Member_id',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='Trainers_id',
            new_name='Trainer_id',
        ),
    ]
