# Generated by Django 5.1.4 on 2024-12-24 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_member_joined_date_trainer_joined_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Name',
            new_name='Member_Name',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='Name',
            new_name='Trainer_Name',
        ),
    ]
