# Generated by Django 5.1.4 on 2024-12-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_name_member_member_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Address',
            new_name='Member_Address',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Email',
            new_name='Member_Email',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Phone_number',
            new_name='Member_Phone_number',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='Address',
            new_name='Trainer_Address',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='Email',
            new_name='Trainer_Email',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='Phone_number',
            new_name='Trainer_Phone_number',
        ),
        migrations.RemoveField(
            model_name='member',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='joined_date',
        ),
        migrations.AddField(
            model_name='member',
            name='Member_Joined_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='Trainer_Joined_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
