# Generated by Django 5.1.4 on 2024-12-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_address_member_member_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Member_Joined_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Trainer_Joined_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
