# Generated by Django 5.1.4 on 2024-12-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_member_member_joined_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Membership_id', models.IntegerField()),
                ('Plan', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
