# Generated by Django 5.1.4 on 2024-12-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_membership_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_id', models.IntegerField()),
                ('Class_name', models.CharField(max_length=100)),
                ('Trainer_id', models.IntegerField()),
                ('Schedule', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='Membership_Plan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membership_plan',
            name='cost',
            field=models.FloatField(),
        ),
    ]
