# Generated by Django 5.1.4 on 2024-12-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_classe_member_membership_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_id', models.IntegerField()),
                ('Member_id', models.IntegerField()),
                ('Payment_through', models.CharField(max_length=100)),
                ('Payment_date', models.DateTimeField(blank=True, null=True)),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
    ]
