# Generated by Django 5.1.4 on 2024-12-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_payments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
    ]
