# Generated by Django 5.1.4 on 2024-12-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_payments_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership_plan',
            old_name='cost',
            new_name='Cost',
        ),
        migrations.AddField(
            model_name='membership_plan',
            name='Duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
