# Generated by Django 5.1.4 on 2024-12-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_cost_membership_plan_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership_plan',
            name='Duration',
            field=models.CharField(default='1 month', max_length=50),
        ),
    ]
