# Generated by Django 5.1.4 on 2024-12-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_membership_plan_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership_plan',
            name='Duration',
            field=models.CharField(max_length=50, null='True'),
        ),
    ]
