# Generated by Django 5.1.4 on 2025-01-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_creationdate_booking_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='General Category', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(default='Pending', max_length=300),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(default='Not Provided', max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(default='Not Provided', max_length=15),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='duration',
            field=models.CharField(default='1 Month', max_length=50),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AlterField(
            model_name='package',
            name='duration',
            field=models.CharField(default='1 Month', max_length=50),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(default='General Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='packagetype',
            name='name',
            field=models.CharField(default='General Package', max_length=200),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='signup',
            name='address',
            field=models.CharField(default='Not Provided', max_length=200),
        ),
        migrations.AlterField(
            model_name='signup',
            name='city',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AlterField(
            model_name='signup',
            name='mobile',
            field=models.CharField(default='Not Provided', max_length=15),
        ),
        migrations.AlterField(
            model_name='signup',
            name='state',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='address',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.EmailField(default='Not Provided', max_length=254),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='expertise',
            field=models.TextField(default='General Trainer'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='phone_number',
            field=models.CharField(default='Not Provided', max_length=15),
        ),
    ]
