# Generated by Django 5.1.4 on 2025-01-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_booking_booking_number_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipplan',
            options={'verbose_name': 'Membership Plan', 'verbose_name_plural': 'Membership Plans'},
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='plan_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
