# Generated by Django 5.1.4 on 2025-01-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_class_member_trainer_remove_attendance_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_id', models.IntegerField(blank=True, null=True)),
                ('Class_name', models.CharField(max_length=100, null=True)),
                ('Trainer_id', models.IntegerField(blank=True, null=True)),
                ('Schedule', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Membership_id', models.IntegerField(blank=True, null=True)),
                ('Plan', models.CharField(max_length=100, null=True)),
                ('Duration', models.CharField(max_length=50, null='True')),
                ('Cost', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership_plan',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member_joined_date',
            new_name='Member_Joined_date',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_date',
            new_name='Payment_date',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_through',
            new_name='Payment_through',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='trainer_joined_date',
            new_name='Trainer_Joined_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_phone_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='member',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='trainer_address',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='trainer_email',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='trainer_name',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='trainer_phone_number',
        ),
        migrations.AddField(
            model_name='member',
            name='Member_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='Member_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='Payment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='Trainer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='MembershipPlan',
        ),
        migrations.AddField(
            model_name='member',
            name='Membership_Plan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='Member_Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='Member_Email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='Member_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='Member_Phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='Status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='Expertise',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='Trainer_Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='Trainer_Email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='Trainer_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='Trainer_Phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
