# Generated by Django 5.1.4 on 2025-01-08 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_classe_membership_plan_remove_member_membership_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Membership_Plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.membership_plan'),
        ),
    ]
