# Generated by Django 5.1.4 on 2025-01-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_booking_category_class_membershipplan_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='packagename',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
