# Generated by Django 5.1.4 on 2025-01-08 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_package_packagename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='packagename',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.packagetype'),
        ),
    ]
