# Generated by Django 5.1.4 on 2025-01-23 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_class_name_alter_member_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.packagetype'),
        ),
    ]
