# Generated by Django 5.1.4 on 2025-01-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_member_membership_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership_plan',
        ),
        migrations.DeleteModel(
            name='MembershipPlan',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
