# Generated by Django 5.1.5 on 2025-02-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_product_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='signed_field_names',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='product_delivery_charge',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='product_service_charge',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='payment',
            name='product_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_uuid',
            field=models.CharField(max_length=255),
        ),
    ]
