# Generated by Django 5.1.4 on 2025-02-05 13:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_rename_signed_field_names_payment_product_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='quantity',
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.booking'),
        ),
        migrations.AddField(
            model_name='payment',
            name='creationdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='eSewa', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not Updated Yet'), (2, 'Partial Payment'), (3, 'Full Payment')], default=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.signup'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_uuid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
