# Generated by Django 5.1.5 on 2025-02-17 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_regtrainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regtrainer',
            old_name='user',
            new_name='trainer',
        ),
    ]
