# Generated by Django 5.1.7 on 2025-03-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
