# Generated by Django 5.1.7 on 2025-03-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_trainer_email_remove_trainer_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
