# Generated by Django 5.1.7 on 2025-04-02 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0039_trainer_email_trainer_first_name_trainer_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("schedule", models.CharField(max_length=255)),
                ("capacity", models.PositiveIntegerField()),
                ("creationdate", models.DateTimeField(auto_now_add=True)),
                ("members", models.ManyToManyField(blank=True, to="app.signup")),
                (
                    "trainer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.trainer",
                    ),
                ),
            ],
        ),
    ]
