# Generated by Django 5.1.7 on 2025-04-08 16:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0041_memberattendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberattendance",
            name="time",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
