# Generated by Django 5.1.7 on 2025-04-10 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_memberattendance_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="members",
        ),
        migrations.AddField(
            model_name="class",
            name="members",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.signup",
            ),
        ),
    ]
