# Generated by Django 5.1.7 on 2025-04-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_remove_class_members_class_members"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="members",
        ),
        migrations.AddField(
            model_name="class",
            name="members",
            field=models.ManyToManyField(blank=True, to="app.signup"),
        ),
    ]
