# Generated by Django 5.1.7 on 2025-04-10 13:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0044_remove_class_members_class_members"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="schedule",
        ),
        migrations.AddField(
            model_name="class",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("Sunday", "Sunday"),
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                ],
                default="Monday",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
