# Generated by Django 5.1.7 on 2025-04-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0045_remove_class_schedule_class_day_of_week_class_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="day_of_week",
        ),
        migrations.RemoveField(
            model_name="class",
            name="time",
        ),
        migrations.AddField(
            model_name="class",
            name="schedule",
            field=models.CharField(default="To be determined", max_length=255),
        ),
    ]
