# Generated by Django 5.1.7 on 2025-04-15 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0046_remove_class_day_of_week_remove_class_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="booking",
        ),
        migrations.RemoveField(
            model_name="paymenthistory",
            name="booking",
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.IntegerField(choices=[(1, "Paid")], default=1),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="status",
            field=models.IntegerField(choices=[(1, "Paid")], default=1),
        ),
        migrations.CreateModel(
            name="Enroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrollnumber",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("status", models.IntegerField(choices=[(1, "Paid")], default=1)),
                ("creationdate", models.DateTimeField(auto_now_add=True)),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.package",
                    ),
                ),
                (
                    "register",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.signup",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="payment",
            name="enroll",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.enroll",
            ),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="enroll",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.enroll",
            ),
        ),
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
