# Generated by Django 5.1.7 on 2025-05-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0047_remove_payment_booking_remove_paymenthistory_booking_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("on_leave", "On Leave"),
                    ("inactive", "Inactive"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
