# Generated by Django 5.1.7 on 2025-05-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0048_trainer_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenthistory",
            name="payment_method",
            field=models.CharField(default="eSewa", max_length=50),
        ),
        migrations.AlterField(
            model_name="enroll",
            name="status",
            field=models.IntegerField(choices=[(1, "Paid"), (0, "Unpaid")], default=1),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.IntegerField(choices=[(1, "Paid"), (0, "Unpaid")], default=1),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="status",
            field=models.IntegerField(choices=[(1, "Paid"), (0, "Unpaid")], default=1),
        ),
    ]
