# Generated by Django 5.1.7 on 2025-05-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0051_alter_chatroom_unique_together_message_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="room",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.DeleteModel(
            name="ChatRoom",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
