# Generated by Django 5.1.7 on 2025-05-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0053_trainer_profile_photo_trainer_profile_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
