# Generated by Django 5.1.7 on 2025-05-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0055_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="cv",
            field=models.FileField(blank=True, null=True, upload_to="trainer_cvs/"),
        ),
    ]
