# Generated by Django 5.1.7 on 2025-05-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0056_trainer_cv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("on_leave", "On Leave"),
                    ("inactive", "Inactive"),
                ],
                default="inactive",
                max_length=10,
            ),
        ),
    ]
